name: Build

on: [push]

jobs:
  BuildJob:
    name: Build
    runs-on: macos-latest
    steps:
      - shell: bash
        run: |
          pwd
          ls
          sed -i '' "s/-Werror //" Makefile
          make -j$(sysctl -n hw.logicalcpu)
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Pongo
          path: build/Pongo.bin
