name: Build

on: [push]

jobs:
  BuildJob:
    name: SomeThing
    runs-on: macos-latest
    steps:
      - shell: bash
        run: |
          sed -i '' "s/-Werror //" Makefile
          make -j$(sysctl -n hw.logicalcpu)
      - name: Resuls
        uses: actions/upload-artifact@v3
        with:
          name: Pongo
          path: build/Pongo.bin
